### ISSUE TITLE
FF 108.0.2 on Linux

### ISSUE THREAD

**Issue by eirenicon** [magnusarge/Mastodon-Air#1]
I am trying to run on Debian Linux 6.0.6 (kernel) using FF 108.0.2  I am unable to access the settings for Mastodon Air (anywhere,  I have hunted and not found the settings as described in your docs.)  'tis sad.

**Comment by magnusarge** [comment]
Which version of Mastodon Air do you have?
2.0.9 doesn't have configuration options yet.
Did you install it from the Firefox addon store?

**Comment by eirenicon** [comment]
I found everything in the FF settings.  FWIW I prefer to select colors by using hex or alternatively rgba.  With those,  I can match things with my desktop. I'm 'only' a little bit picky.  ;)

**Comment by magnusarge** [comment]
If you want to make your hands dirty, chrome/js/themebackgrounds.js is the file where the colours are defined.

Did I understand correctly that you got a solution to your problem?

**Comment by eirenicon** [comment]
I think so.  Nice work!
